# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

  platform :ios, '15.1'
  prepare_react_native_project!

  ENV['RCT_NEW_ARCH_ENABLED'] = '1'

  target 'CurrencyCamera' do
    config = use_native_modules!

    use_react_native!(
      :path           => config[:reactNativePath],
      :app_path       => "#{Pod::Config.instance.installation_root}/..",
      :hermes_enabled => true,
      :fabric_enabled => true,
      :new_arch_enabled => true
    )

    post_install do |installer|
      react_native_post_install(
        installer,
        config[:reactNativePath],
        :mac_catalyst_enabled => false,
      )

      # Optional: reduce Xcode 16 “non-modular include” noise
      installer.pods_project.targets.each do |t|
        t.build_configurations.each do |bc|
          bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
          bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
          bc.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
        end
      end
    end
  end
